Desktop-view
Devsalmasaeed/travel-website pull request #1
Opened 2024-08-07 11:06 UTC by Devsalmasaeed

Added html and css files

2024-08-11 11:23 UTC, devalibello commented on index.html
> +    </section>
Comment on Indentation: The section was correctly implemented but the children tags within the section tag should be indented. E.g 
<section>
    <div>Text 1</div>
    <div>Text 1</div>
</section>

Go through your ...

2024-08-11 11:24 UTC, devalibello commented on index.html
> +        <span>We have more than 1000+ destinations you can choose.</span>
Remove all white spaces within your HTML file

2024-08-30 19:09 UTC, Xfarouq commented
## Nice Work!💯
- Code looks good
- Correctly Applied the use of Semantics
- Good indentation too

# Code Defect
- Put in your mobile screen size code into your Desktop screen code and your good to go✅

2024-08-30 19:11 UTC, Xfarouq requested changes

2024-08-30 19:11 UTC, Xfarouq commented on styles.css
## Nice Work!💯
- Code looks good
- Correctly Applied the use of Semantics
- Good indentation too

# Code Defect
- Put in your mobile screen size code into your Desktop screen code and your good to go✅

2024-09-07 20:06 UTC, merged